Repository gutanbug/renew-sw-mentoring, pull requests merged in 2024-03, with the labels that each got.

#41 feat #39 : 팀 별 성공한 미션을 관리하는 엔티티 추가 및 미션보드 엔티티 수정
  src/main/java/com/renew/sw/mentoring/domain/completedmission/model/entity/CompletedMission.java
  src/main/java/com/renew/sw/mentoring/domain/mission/model/entity/Mission.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/type/MissionBoard.java
  src/main/java/com/renew/sw/mentoring/domain/team/controller/TeamController.java
  src/main/java/com/renew/sw/mentoring/domain/team/model/entity/Team.java
Labels: enhancement, fix

#52 feat #38 : 미션 인증글 서비스 구현
  src/main/java/com/renew/sw/mentoring/domain/post/controller/MissionBoardController.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/request/RequestCreateMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/repository/MissionBoardRepository.java
  src/main/java/com/renew/sw/mentoring/domain/post/repository/spec/PostSpec.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/MissionBoardService.java
Labels: enhancement, fix

#53 feat #38 : 미션 인증글 서비스 구현
  src/main/java/com/renew/sw/mentoring/domain/post/controller/MissionBoardController.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/request/RequestCreateMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/repository/MissionBoardRepository.java
  src/main/java/com/renew/sw/mentoring/domain/post/repository/spec/PostSpec.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/MissionBoardService.java
Labels: enhancement, fix

#55 feat #14 : 성공한 미션 상세 조회 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/completedmission/service/CompletedMissionService.java
  src/main/java/com/renew/sw/mentoring/domain/team/controller/TeamController.java
Labels: enhancement

#56 feat: 미션 인증 글 수정, 삭제 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/post/controller/MissionBoardController.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/request/RequestUpdateMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/MissionBoardService.java
Labels: enhancement

#57 feat #38 : 미션 인증 글 수정, 삭제 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/post/controller/MissionBoardController.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/request/RequestUpdateMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/MissionBoardService.java
Labels: enhancement

#58 fix : Mission 파싱 중 미션 이름 앞에 숫자 제거하는 로직으로 수정
  src/main/java/com/renew/sw/mentoring/domain/excel/MissionParser.java
Labels: fix

#61 feat #38 : 관리자 권한의 미승인 인증글 조회 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/admin/controller/AdminController.java
  src/main/java/com/renew/sw/mentoring/domain/admin/service/AdminService.java
  src/main/java/com/renew/sw/mentoring/domain/excel/MissionParser.java
  src/main/java/com/renew/sw/mentoring/domain/mission/repository/BonusMissionRepository.java
  src/main/java/com/renew/sw/mentoring/domain/post/controller/MissionBoardController.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/list/SummarizedMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/repository/MissionBoardRepository.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/GenericPostService.java
  src/main/java/com/renew/sw/mentoring/domain/post/service/MissionBoardService.java
Labels: enhancement, fix

#67 feat #65 : 미션 승인이 완료된 글을 취소하는 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/admin/controller/AdminController.java
  src/main/java/com/renew/sw/mentoring/domain/admin/service/AdminService.java
  src/main/java/com/renew/sw/mentoring/domain/completedmission/repository/CompletedMissionRepository.java
  src/main/java/com/renew/sw/mentoring/domain/post/exception/MissionBoardNotAcceptedException.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/type/MissionBoard.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
Labels: enhancement

#69 feat #65 : 관리자를 통한 미션 인증글 승인 기능 추가
  src/main/java/com/renew/sw/mentoring/domain/admin/controller/AdminController.java
  src/main/java/com/renew/sw/mentoring/domain/admin/service/AdminService.java
  src/main/java/com/renew/sw/mentoring/domain/post/exception/AlreadyMissionBoardAcceptedException.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
Labels: enhancement

#73 test #65 : 미션 인증글 승인에 대한 테스트 코드 작성
  src/test/java/com/renew/sw/mentoring/domain/admin/service/AdminServiceTest.java
  src/test/java/com/renew/sw/mentoring/mock/BonusMissionMock.java
  src/test/java/com/renew/sw/mentoring/mock/MissionBoardMock.java
  src/test/java/com/renew/sw/mentoring/mock/MissionMock.java
  src/test/java/com/renew/sw/mentoring/mock/TeamMock.java
  src/test/java/com/renew/sw/mentoring/mock/UserMock.java
Labels: test

#75 test #65 : 미션 인증 글 승인 거부에 대한 테스트 코드 작성
  src/test/java/com/renew/sw/mentoring/domain/admin/service/AdminServiceTest.java
Labels: test

#77 test #65 : 승인 완료된 글에 대한 취소 작업 테스트 코드 작성
  src/test/java/com/renew/sw/mentoring/domain/admin/service/AdminServiceTest.java
Labels: test

#85 fix: 미션 인증글, 공지글 response dto 수정
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseSingleNoticeDto.java
Labels: fix

#86 fix: 미션 인증글, 공지글 response dto 수정
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseMissionBoardDto.java
  src/main/java/com/renew/sw/mentoring/domain/post/model/entity/dto/response/ResponseSingleNoticeDto.java
Labels: fix

#88 fix: 전체 팀 조회에서 팀원 조회도 가능하도록 수정
  README.md
  src/main/java/com/renew/sw/mentoring/domain/team/model/dto/list/SummarizedTeamDto.java
  src/main/java/com/renew/sw/mentoring/domain/team/service/TeamService.java
  src/test/java/com/renew/sw/mentoring/domain/team/controller/TeamControllerTest.java
  src/test/java/com/renew/sw/mentoring/domain/team/service/TeamServiceTest.java
  src/test/java/com/renew/sw/mentoring/mock/UserMock.java
  src/test/java/com/renew/sw/mentoring/util/EntityUtil.java
  src/test/java/com/renew/sw/mentoring/util/FieldReflector.java
  src/test/java/com/renew/sw/mentoring/util/RandomGen.java
Labels: test, fix
